# Generated by Django 5.2.7 on 2026-01-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emotion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='emotion',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='emotion',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Emotion',
        ),
    ]
