# Generated by Django 5.2.7 on 2026-01-07 03:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managecourse',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='managecourse',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managecourse',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
