# Generated by Django 5.2.7 on 2026-01-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_options_course_video_lesson_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managecourse',
            name='status',
            field=models.CharField(choices=[('UNENROLLED', 'Unenrolled'), ('ENROLLED', 'Enrolled'), ('COMPLETED', 'Completed')], default='UNENROLLED', max_length=20),
        ),
    ]
