# Generated by Django 5.2.7 on 2026-01-09 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_managecourse_active_managecourse_created_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'role': 'INSTRUCTOR'}, on_delete=django.db.models.deletion.RESTRICT, related_name='owned_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
