# Generated by Django 5.2.7 on 2026-01-10 04:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_instructor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managecourse',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='managecourse',
            unique_together={('student', 'course')},
        ),
    ]
