# Generated by Django 5.2.7 on 2026-01-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='type',
            field=models.CharField(choices=[(1, 'Like'), (2, 'Love'), (3, 'Funny'), (4, 'Sad')], max_length=10),
        ),
    ]
