# Generated by Django 5.2.7 on 2026-01-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_emotion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Like'), (2, 'Love'), (3, 'Funny'), (4, 'Sad')]),
        ),
    ]
