# Generated by Django 5.2.7 on 2026-01-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_transaction_provider_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
