# Generated by Django 5.2.7 on 2026-01-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_transaction_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(help_text='vnd, usd', max_length=10),
        ),
    ]
