# Generated by Django 5.2.7 on 2026-01-09 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_instructor'),
        ('payments', '0006_remove_transaction_payment_method'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactiondetail',
            unique_together={('transaction', 'courses')},
        ),
    ]
