# Generated by Django 5.2.7 on 2026-01-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_managecourse_options_and_more'),
        ('payments', '0007_alter_transactiondetail_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiondetail',
            old_name='courses',
            new_name='course',
        ),
        migrations.AlterUniqueTogether(
            name='transactiondetail',
            unique_together={('transaction', 'course')},
        ),
    ]
